In [89]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [90]:
data= pd.read_csv("TMDB_movie_dataset_v11.csv")

In [91]:
data.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [92]:
data.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords'],
      dtype='object')

In [93]:
data=data[['id', 'title', 'overview', 'genres', 'keywords']]

In [94]:
data.head()

,id,title,overview,genres,keywords
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com..."

In [95]:
data['keywords']= data['overview']+data['genres']

In [96]:
data.head()

,id,title,overview,genres,keywords
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","Action, Science Fiction, Adventure","Cobb, a skilled thief who commits corporate es..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"Adventure, Drama, Science Fiction",The adventures of a group of explorers who mak...
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller",Batman raises the stakes in his war on crime. ...
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction","In the 22nd century, a paraplegic Marine is di..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure",When an unexpected enemy emerges and threatens...

In [97]:
data= data.drop(columns=['overview', 'genres'])

In [98]:
data.head()

       id            title                                           keywords
0   27205        Inception  Cobb, a skilled thief who commits corporate es...
1  157336     Interstellar  The adventures of a group of explorers who mak...
2     155  The Dark Knight  Batman raises the stakes in his war on crime. ...
3   19995           Avatar  In the 22nd century, a paraplegic Marine is di...
4   24428     The Avengers  When an unexpected enemy emerges and threatens...

In [99]:
data.to_csv("data.csv", index=False)

In [100]:
data.isnull().sum()

id          0
title       0
keywords    0
dtype: int64

In [101]:
data = data.dropna(subset=['id', 'title', 'keywords'])
data = data[(data['id']!= '') & (data['title'] != '') & (data['keywords'] != '')]

In [102]:
data.isnull().sum()

id          0
title       0
keywords    0
dtype: int64

In [103]:
cv = CountVectorizer(max_features=10000, stop_words='english')

In [104]:
vector_data= cv.fit_transform(data['keywords'].values.astype('U')).toarray()

In [105]:
vector_data.shape

(3000, 10000)

In [106]:
similarity= cosine_similarity(vector_data)

In [107]:
similarity

array([[1.        , 0.12838815, 0.02860648, ..., 0.0232747 , 0.        ,
        0.08320503],
       [0.12838815, 1.        , 0.03183035, ..., 0.        , 0.        ,
        0.06172134],
       [0.02860648, 0.03183035, 1.        , ..., 0.05193297, 0.        ,
        0.02062842],
       ...,
       [0.0232747 , 0.        , 0.05193297, ..., 1.        , 0.03850428,
        0.01678363],
       [0.        , 0.        , 0.        , ..., 0.03850428, 1.        ,
        0.04588315],
       [0.08320503, 0.06172134, 0.02062842, ..., 0.01678363, 0.04588315,
        1.        ]], shape=(3000, 3000))

In [108]:
def recommend(movie_title):
    index = data[data['title'] == movie_title].index[0]
    similar_movies = sorted(((i, similarity[index][i])
    for i in range(len(similarity[index]))), key=lambda x: x[1], reverse=True)[1:6]
    recommended_titles = [data.iloc[movie[0]].title for movie in similar_movies]
    return recommended_titles

In [109]:
recommended_movies= recommend("The Dark Knight")
for movie_title in recommended_movies:
    print(movie_title)

The Dark Knight Rises
Batman
Batman Forever
Batman: The Killing Joke
The Batman

In [110]:
import pickle

In [111]:
pickle.dump(data, open('movie_list.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [112]:
pickle.load(open('similarity.pkl', 'rb'))

array([[1.        , 0.12838815, 0.02860648, ..., 0.0232747 , 0.        ,
        0.08320503],
       [0.12838815, 1.        , 0.03183035, ..., 0.        , 0.        ,
        0.06172134],
       [0.02860648, 0.03183035, 1.        , ..., 0.05193297, 0.        ,
        0.02062842],
       ...,
       [0.0232747 , 0.        , 0.05193297, ..., 1.        , 0.03850428,
        0.01678363],
       [0.        , 0.        , 0.        , ..., 0.03850428, 1.        ,
        0.04588315],
       [0.08320503, 0.06172134, 0.02062842, ..., 0.01678363, 0.04588315,
        1.        ]], shape=(3000, 3000))